// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGk5iwgRjCeeYjXBjeWdclEy04KmM5P8',
    appId: '1:524286329619:web:b4c483f68d187792c890e6',
    messagingSenderId: '524286329619',
    projectId: 'yachat-77ac7',
    authDomain: 'yachat-77ac7.firebaseapp.com',
    storageBucket: 'yachat-77ac7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XM_5iJBlebS1aaxapMeWJ4eITxgDFEU',
    appId: '1:524286329619:android:886c89f7b3110167c890e6',
    messagingSenderId: '524286329619',
    projectId: 'yachat-77ac7',
    storageBucket: 'yachat-77ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaqttcQXbyWK1Njpj-ObR2RGo69IzTc0',
    appId: '1:524286329619:ios:f1c152a8a878a901c890e6',
    messagingSenderId: '524286329619',
    projectId: 'yachat-77ac7',
    storageBucket: 'yachat-77ac7.appspot.com',
    iosClientId: '524286329619-s8f56ma1kdndse5tar3he5qo938arf3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.yachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaqttcQXbyWK1Njpj-ObR2RGo69IzTc0',
    appId: '1:524286329619:ios:f1c152a8a878a901c890e6',
    messagingSenderId: '524286329619',
    projectId: 'yachat-77ac7',
    storageBucket: 'yachat-77ac7.appspot.com',
    iosClientId: '524286329619-s8f56ma1kdndse5tar3he5qo938arf3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.yachat',
  );
}
